"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$nix_shell\
$hostname\
$username\
$directory\
${custom.dirlvl}\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$time\
$cmd_duration\
$line_break$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
format = "$symbol "

[os.symbols]
Alpaquita = " "
Alpine = "[  ](bg:teal fg:base)"
AlmaLinux = " "
Amazon = "[  ](bg:peach fg:base)"
Android = "[  ](bg:green fg:base)"
Arch = "[  ](bg:sky fg:base)"
Artix = "[  ](bg:sky fg:base)"
CentOS = "[  ](bg:lavender fg:base)"
Debian = "[  ](bg:red fg:base)"
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = "[  ](bg:blue fg:base)"
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = "[ 󰣨 ](bg:green fg:base)"
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = "[ 󰌽 ](bg:peach fg:base)"
Mabox = " "
Macos = "[ 󰀵 ](bg:text fg:base)"
Manjaro = "[  ](bg:green fg:base)"
Mariner = " "
MidnightBSD = " "
Mint = "[ 󰣭 ](bg:green fg:base)"
NetBSD = " "
NixOS = "[  ](blue)"
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = "[  ](bg:red fg:base)"
Redhat = "[ 󱄛 ](bg:red fg:base)"
RedHatEnterprise = "[ 󱄛 ](bg:red fg:base)"
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = "[  ](bg:green fg:base)"
Ubuntu = "[  ](bg:peach fg:base)"
Unknown = " "
Void = " "
Windows = "[ 󰍲 ](bg:sapphire fg:base)"

[nix_shell]
style = "blue italic"
format = '[nix-shell ]($style)'

[hostname]
style = "mauve"
ssh_symbol = "[ 󰛳 ](bg:surface0 fg:$style)"
format = "$ssh_symbol[$hostname ](bg:surface0 fg:text)"

[username]
show_always = true
style_user = "sky"
style_root = "red"
format = '[ ](fg:$style bg:surface0)[ $user ](text bg:surface0)'
aliases = { "root" = "" }

[directory]
style = "yellow"
format = "[ ](fg:$style bg:surface0)[ $path ](text bg:surface0)"
truncation_length = 3
truncation_symbol = ""

#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = "󰝚 "
#"Pictures" = " "
#"Developer" = "󰲋 "

[custom.dirlvl]
command = 'echo $BVKT_DEPTH'
when = ''' test $BVKT_DEPTH != 0 '''
format = '[$output ](bg:surface0 fg:yellow italic)'

[git_branch]
symbol = ""
style = "bg:surface0 fg:peach"
format = '[ $symbol]($style)[ $branch ](bg:surface0 fg:text)'

[git_status]
style = "bg:surface0 fg:peach"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:base"
format = '[[ $symbol( $context) ](fg:#83a598 bg:base)]($style)'

[time]
disabled = false
time_format = "%R"
style = "green"
format = '[ 󰃰 ](bg:surface0 fg:$style)[$time ](bg:surface0 fg:text)'

[cmd_duration]
min_time = 500
min_time_to_notify = 45000
show_milliseconds = true
show_notifications = true
style = "green"
format = '[$duration ](bg:surface0 fg:$style italic)'

[line_break]
disabled = false

[character]
success_symbol = "[ ](green)"
error_symbol =   "[ ](red)"
vimcmd_symbol =  "[ ](sapphire)"
vimcmd_replace_one_symbol = '[ ](peach)'
vimcmd_replace_symbol = '[ ](peach)'
vimcmd_visual_symbol = '[ ](mauve)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
